// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry/chat.proto

package entry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BroadcastRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp            int32    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRequest) Reset()         { *m = BroadcastRequest{} }
func (m *BroadcastRequest) String() string { return proto.CompactTextString(m) }
func (*BroadcastRequest) ProtoMessage()    {}
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82c3cbe99389f4f3, []int{0}
}

func (m *BroadcastRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRequest.Unmarshal(m, b)
}
func (m *BroadcastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRequest.Marshal(b, m, deterministic)
}
func (m *BroadcastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRequest.Merge(m, src)
}
func (m *BroadcastRequest) XXX_Size() int {
	return xxx_messageInfo_BroadcastRequest.Size(m)
}
func (m *BroadcastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRequest proto.InternalMessageInfo

func (m *BroadcastRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BroadcastRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *BroadcastRequest) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BroadcastResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp            int32    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastResponse) Reset()         { *m = BroadcastResponse{} }
func (m *BroadcastResponse) String() string { return proto.CompactTextString(m) }
func (*BroadcastResponse) ProtoMessage()    {}
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82c3cbe99389f4f3, []int{1}
}

func (m *BroadcastResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastResponse.Unmarshal(m, b)
}
func (m *BroadcastResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastResponse.Marshal(b, m, deterministic)
}
func (m *BroadcastResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastResponse.Merge(m, src)
}
func (m *BroadcastResponse) XXX_Size() int {
	return xxx_messageInfo_BroadcastResponse.Size(m)
}
func (m *BroadcastResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastResponse proto.InternalMessageInfo

func (m *BroadcastResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BroadcastResponse) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *BroadcastResponse) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*BroadcastRequest)(nil), "entry.BroadcastRequest")
	proto.RegisterType((*BroadcastResponse)(nil), "entry.BroadcastResponse")
}

func init() {
	proto.RegisterFile("entry/chat.proto", fileDescriptor_82c3cbe99389f4f3)
}

var fileDescriptor_82c3cbe99389f4f3 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x80, 0xad, 0x5a, 0xa5, 0x39, 0xd5, 0x5c, 0x0c, 0xa2, 0x58, 0x7a, 0xea, 0xc5, 0x04, 0xf4,
	0x05, 0xa4, 0x8f, 0x50, 0x3d, 0x79, 0x50, 0xd2, 0x38, 0xa4, 0x2d, 0xa4, 0x89, 0x99, 0xa9, 0xe0,
	0xdb, 0x0b, 0x59, 0xca, 0x96, 0xdd, 0xeb, 0xde, 0x66, 0xbe, 0x61, 0x7e, 0xbe, 0x61, 0x25, 0xcc,
	0x14, 0xff, 0x94, 0x19, 0x34, 0xc9, 0x10, 0x3d, 0x79, 0x9e, 0x27, 0x52, 0x7f, 0xb2, 0xb2, 0x8d,
	0x5e, 0x7f, 0x1b, 0x8d, 0xd4, 0xc1, 0xcf, 0x02, 0x48, 0x5c, 0xb0, 0x6b, 0x07, 0x88, 0xda, 0x82,
	0xc8, 0xaa, 0xac, 0x29, 0xba, 0x35, 0xe5, 0x9c, 0x5d, 0x2e, 0x08, 0x51, 0x9c, 0x27, 0x9c, 0x62,
	0x7e, 0xcf, 0x0a, 0x1a, 0x1d, 0x20, 0x69, 0x17, 0xc4, 0x45, 0x95, 0x35, 0x79, 0xb7, 0x07, 0xf5,
	0x17, 0xbb, 0xd9, 0xcc, 0xc7, 0xe0, 0x67, 0x84, 0x53, 0x2e, 0x78, 0x7e, 0xdf, 0x08, 0xbc, 0x41,
	0xfc, 0x1d, 0x0d, 0xf0, 0x57, 0x56, 0xf4, 0x2b, 0xe3, 0xb7, 0x32, 0x99, 0xca, 0x43, 0xcd, 0x3b,
	0x71, 0x5c, 0xd8, 0xdd, 0x57, 0x9f, 0xb5, 0x8f, 0x1f, 0x0f, 0x76, 0xa4, 0x61, 0xe9, 0xa5, 0xf1,
	0x4e, 0x4d, 0x76, 0xf2, 0xca, 0xc6, 0x60, 0x9e, 0xac, 0x57, 0xa9, 0xa9, 0xbf, 0x4a, 0x5f, 0x7c,
	0xf9, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x63, 0x5e, 0x59, 0x59, 0x01, 0x00, 0x00,
}
